---
abstract: 'Flatten a web pages deeply and make it portable'
author:
  - 'sugama <sugama@jamadam.com>'
build_requires:
  Test::More: 0.98
  Test::UseAllModules: 0.10
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Flatten
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: 5.41
  WWW::Crawler::Mojo: 0.05
resources: {}
version: 0.01
